name: Release and Publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: 'choice'
        description: 'Release type'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
      version_message:
        description: 'Upgrade reasons (optional)'
        required: false


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Bump version
        run: |
          release_type=${{ github.event.inputs.release_type }}
          commit_message=${{ github.event.inputs.version_message }}
          npm version $release_type ${commit_message && `-m "${commit_message}"`}

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push commit and tags to the repo
        run: git push --follow-tags
